import { contextBridge, ipcRenderer } from 'electron';
contextBridge.exposeInMainWorld('jarvis', {
    getSettings: () => ipcRenderer.invoke('settings:get'),
    setSettings: (input) => ipcRenderer.invoke('settings:set', input),
    faceProfiles: () => ipcRenderer.invoke('face-profiles:list'),
    saveFaceProfile: (profile) => ipcRenderer.invoke('face-profiles:save', profile),
    deleteFaceProfile: (id) => ipcRenderer.invoke('face-profiles:delete', id),
    clearFaceProfiles: () => ipcRenderer.invoke('face-profiles:clear'),
    listModels: (provider) => ipcRenderer.invoke('models:list', provider),
    diagnostics: () => ipcRenderer.invoke('system:diagnostics'),
    networkStatus: () => ipcRenderer.invoke('system:network'),
    deviceIdentity: () => ipcRenderer.invoke('system:identity'),
    requestTelemetry: () => ipcRenderer.invoke('system:telemetry-request'),
    onSystemTelemetry: (callback) => { const handler = (_event, payload) => callback(payload); ipcRenderer.on('system:telemetry', handler); return () => ipcRenderer.removeListener('system:telemetry', handler); },
    adb: (command) => ipcRenderer.invoke('system:adb', command),
    adbStatus: () => ipcRenderer.invoke('system:adb-status'),
    currentLocation: () => ipcRenderer.invoke('system:location'),
    weather: (latitude, longitude) => ipcRenderer.invoke('system:weather', latitude, longitude),
    searchLocation: (query) => ipcRenderer.invoke('system:map-search', query),
    systemLogs: () => ipcRenderer.invoke('system:logs'),
    query: (input) => ipcRenderer.invoke('assistant:query', input),
    pythonCapability: (input) => ipcRenderer.invoke('python:capability', input),
    voiceEmbed: async (audioBase64) => { const result = await ipcRenderer.invoke('python:capability', { operation: 'voice_embed', payload: { audioBase64 } }); return (result?.embedding || []); },
    voiceStatus: () => ipcRenderer.invoke('voice:status'),
    sttStart: (language) => ipcRenderer.invoke('stt:start', language),
    sttStatus: () => ipcRenderer.invoke('stt:status'),
    sttStop: () => ipcRenderer.invoke('stt:stop'),
    onSttTranscript: (callback) => { const handler = (_event, payload) => callback(typeof payload === 'string' ? { text: payload } : payload); ipcRenderer.on('stt:transcript', handler); return () => ipcRenderer.removeListener('stt:transcript', handler); },
    onSttError: (callback) => { const handler = (_event, message) => callback(message); ipcRenderer.on('stt:error', handler); return () => ipcRenderer.removeListener('stt:error', handler); },
    speak: (input) => ipcRenderer.invoke('voice:speak', input),
    openUrl: (url) => ipcRenderer.invoke('system:open-url', url),
    requestElevation: () => ipcRenderer.invoke('system:request-elevation'),
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close')
});
